# Imagen base de Astral (uv + python)
FROM ghcr.io/astral-sh/uv:python3.12-alpine

WORKDIR /app
COPY . .

# Asegúrate de que el script tenga permisos de ejecución
# RUN chmod +x install_deps.sh && \
#     apk add bash && \
#     bash install_deps.sh

# Ejecuta la instalación condicional
CMD [ "uv run streamlit run main.py" ]