networks:
  PythonApp:
    driver: bridge
    
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GEMINI_API_KEY=APIKEY
      - API_BACKEND_URL=localhost/8080
    ports:
      - "4560:8501"
    networks:
      - PythonApp
